image:
  repository: 304361287196.dkr.ecr.us-east-1.amazonaws.com/shin/search
  tag: latest

service:
  port: 8087
  containerPort: 8087

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: CONFIG_SERVER_USERNAME
    valueFrom:
      secretKeyRef:
        name: config-server-creds
        key: username
  - name: CONFIG_SERVER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: config-server-creds
        key: password
  - name: AWS_REGION
    value: "us-east-1"

envConfig:
  SHIN_AWS_REGION: "us-east-1"
  OPENSEARCH_COLLECTION_ENDPOINT: ""  # fill with actual OpenSearch endpoint
  VIDEO_PUBLISHED_QUEUE_NAME: "shin-dev-video-published-opensearch-indexer"

serviceAccount:
  create: true
  roleArn: ""  # set to IRSA role ARN from terraform output irsa_role_arns["search"]
