{{- if .Values.envSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-app.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
  annotations:
    # Phase 2: migrate to ExternalSecrets pointing to AWS Secrets Manager
    app.kubernetes.io/managed-by-external-secrets: "false"
type: Opaque
data:
  {{- range $key, $value := .Values.envSecret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
