CREATE SCHEMA IF NOT EXISTS metadata;
CREATE SCHEMA IF NOT EXISTS interaction;

GRANT ALL PRIVILEGES ON SCHEMA metadata TO root;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA metadata TO root;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA metadata TO root;

ALTER DEFAULT PRIVILEGES IN SCHEMA metadata GRANT ALL ON TABLES TO root;
ALTER DEFAULT PRIVILEGES IN SCHEMA metadata GRANT ALL ON SEQUENCES TO root;

ALTER DATABASE shin SET search_path TO metadata, public;
