CREATE SCHEMA IF NOT EXISTS "user";

GRANT ALL PRIVILEGES ON SCHEMA "user" TO root;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "user" TO root;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "user" TO root;

ALTER DEFAULT PRIVILEGES IN SCHEMA "user" GRANT ALL ON TABLES TO root;
ALTER DEFAULT PRIVILEGES IN SCHEMA "user" GRANT ALL ON SEQUENCES TO root;
