spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
  data:
    redis:
      host: redis
      port: 6379
      password: redis
      client-type: lettuce
      lettuce:
        pool:
          enabled: true

