spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///app/config-repo

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.bus: DEBUG
