spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          search-paths: /
          timeout: 10
          force-pull: true

logging:
  level:
    root: WARN
    org.springframework.cloud.config: INFO
    org.springframework.cloud.bus: INFO
