CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255),
    description TEXT,
    creator_id UUID NOT NULL,
    upload_key VARCHAR(255),
    thumbnail_url VARCHAR(255),
    category_id INTEGER REFERENCES videos_categories(id) ON DELETE SET NULL,
    visibility VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    default_language VARCHAR(100),
    published_locale VARCHAR(100),
    only_for_adults BOOLEAN NOT NULL,
    duration decimal,
    resolutions VARCHAR(100),
    published_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    scheduled_publish_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);