apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: shin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: "Shin streaming platform"
  sourceRepos:
    - "*"
  destinations:
    - namespace: shin-dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
