replicaCount: 1

image:
  repository: ""
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}
  roleArn: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080
  containerPort: 8080

ingress:
  enabled: false
  className: "alb"
  annotations: {}
  host: ""
  paths:
    - path: /
      pathType: Prefix

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

jvm:
  toolOptions: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50 -Djava.security.egd=file:/dev/./urandom"

probes:
  liveness:
    path: /actuator/health/liveness
    periodSeconds: 10
    failureThreshold: 3
    initialDelaySeconds: 0
  readiness:
    path: /actuator/health/readiness
    periodSeconds: 5
    failureThreshold: 3
    initialDelaySeconds: 0
  startup:
    path: /actuator/health/liveness
    failureThreshold: 30
    periodSeconds: 5

env: []
# - name: SPRING_PROFILES_ACTIVE
#   value: prod
# - name: MY_SECRET
#   valueFrom:
#     secretKeyRef:
#       name: my-secret
#       key: my-key

envConfig: {}
# NON_SECRET_KEY: value

envSecret:
  create: false
  data: {}
  # SECRET_KEY: base64encodedvalue

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
networkPolicy:
  enabled: false

metrics:
  podAnnotations:
    enabled: true
  podMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    additionalLabels: {}

argocdSyncWave: "1"

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []

terminationGracePeriodSeconds: 45
