name: Setup AWS infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
      destroy:
        description: "Destroy resources instead of applying"
        required: false
        default: "false"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.aws-region }}

      - name: Terraform init
        run: |
          cd infra && terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform destroy
        if: ${{ inputs.destroy == true}}
        id: terraform-destroy
        run: |
          cd infra &&
          terraform destroy -var-file="./environments/${{ inputs.environment }}/terraform.tfvars" -auto-approve

      - name: Terraform plan
        if: ${{ !inputs.destroy }}
        id: terraform-plan
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out="${{ inputs.environment }}.plan"

      - name: Terraform apply
        if: ${{ !inputs.destroy }}
        id: terraform-apply
        run: |
          cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"

      - name: Get Terraform Outputs
        id: outputs
        if: ${{ !inputs.destroy }}
        run: |
          cd infra
          echo "server_task_def_arn=$(terraform output -raw server_task_definition_arn)" >> $GITHUB_OUTPUT
          echo "cli_task_def_arn=$(terraform output -raw cli_task_definition_arn)" >> $GITHUB_OUTPUT
          echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
